### ISSUE TITLE
Property for changing type name case is keyed inconsistently

### ISSUE THREAD

**Issue by emab** [ardeois/graphql-codegen-typescript-mock-data#104]
Currently the property to select a case name change function is `typename` whereas for enum value it is `enumValue`.

To be consistent it would be nice to have consistency between these two properties as it's easy to miss this and end up spending a while debugging why a type name isn't changing (I just did this 😆 ).

**Comment by ardeois** [comment]
@emab indeed that could be confusing, but we're trying to keep the same options as in [typescript plugin](https://the-guild.dev/graphql/codegen/plugins/typescript/typescript)

However I see this should have been named `typeNames` and you did a PR for it already 👍 

![CleanShot 2022-12-23 at 15 26 16](https://user-images.githubusercontent.com/1867939/209402800-88c64a09-7515-49ea-8afd-34c57d535be1.png)
