### ISSUE TITLE
fieldGeneration missing quotes in generated mocks

### ISSUE THREAD

**Issue by toyflish** [ardeois/graphql-codegen-typescript-mock-data#113]
My email default values configured as static strings get translated to mock file without quotes.

versions:

    "@graphql-codegen/cli": "3.0.0",
    "@graphql-codegen/client-preset": "2.0.0",
    "graphql-codegen-typescript-mock-data": "3.2.2",

codegen.yaml

    overwrite: true
    schema: ../../backend/internal/api/graph/
    documents: 'src/flexify.queries.ts'
    generates:
      src/gql_flexify/:
        preset: client
        presetConfig:
          fragmentMasking: false
      src/gql_flexify/mocks.ts:
        plugins:
          - typescript-mock-data:
              typesFile: '../../src/gql_flexify/graphql.ts'
              addTypename: true
              fieldGeneration:
                _all:
                  email: 'customer@test.net'

mock.ts

    export const aGoogleNotificationSettings = (overrides?: Partial<GoogleNotificationSettings>): { __typename: 'GoogleNotificationSettings' } & GoogleNotificationSettings => {
        return {
            __typename: 'GoogleNotificationSettings',
            email: overrides && overrides.hasOwnProperty('email') ? overrides.email! : customer@test.net,
            feedCreatedErrorAlert: overrides && overrides.hasOwnProperty('feedCreatedErrorAlert') ? overrides.feedCreatedErrorAlert! : false,
            planLimitExceededAlert: overrides && overrides.hasOwnProperty('planLimitExceededAlert') ? overrides.planLimitExceededAlert! : false,
            weeklyStatus: overrides && overrides.hasOwnProperty('weeklyStatus') ? overrides.weeklyStatus! : true,
        };
    };

Line 4 has customer@test.net in the correct place but missing the quotation marks.

**Comment by ardeois** [comment]
I think this is because yaml parsing takes the single quotes out
In order to have double or single quotes, did you try to escape them like this:
```
email: \'customer@test.net\'
```

**Comment by toyflish** [comment]
Thanks for your help, it was caused by my yaml config, wrapping in double quotes works fine.
