### ISSUE TITLE
support for enumsAsTypes

### ISSUE THREAD

**Issue by bryantserres** [ardeois/graphql-codegen-typescript-mock-data#117]
may have missed something but is `enumsAsTypes` (https://the-guild.dev/graphql/codegen/plugins/typescript/typescript#enumsastypes) currently supported?

**Comment by ardeois** [comment]
No this is not currently supported.
What would be the use case of having this supported in functions generating mock data?

**Comment by bryantserres** [comment]
it would be useful for defaults with mock data generating functions.

example:
```
enum Status {
  ONLINE
  OFFLINE
}
```

```

**Comment by bryantserres** [comment]
also, willing to put out a PR to add this functionality 🙂

**Comment by ardeois** [comment]
Ah interesting, that makes sense indeed.
Feel free to open a PR to add this functionnality, but make sure to add unit tests, the code is not as clean as I would like, but we try to cover all use cases with unit tests

**Comment by ardeois** [comment]
Fixed in #118
