### ISSUE TITLE
mocks - useImplementingTypes errors

### ISSUE THREAD

**Issue by maord-upstream** [ardeois/graphql-codegen-typescript-mock-data#121]
Hello,

In my codegenConfig file, I added the "useImplementingTypes" property for fix types, but now my mocks file contains errors.

For example: 
"The expected type comes from property 'foo' which is declared here on type '{ __typename: "TEST"; } & Test".

Could you please tell me how to fix this?
Thanks

**Comment by ardeois** [comment]
Sorry but `useImplementingTypes` is currently not supported on this plugin

**Comment by ardeois** [comment]
Not at the moment, but feel free to open a PR if you want it

**Comment by maordaniel** [comment]
I've opened a PR, please review it.

**Comment by ardeois** [comment]
Implemented in 3.4.1
