### ISSUE TITLE
Max stack trace error

### ISSUE THREAD

**Issue by molandim** [ardeois/graphql-codegen-typescript-mock-data#13]
On my schema I have a recursive property.

```
// simplified object for clarity 
type Experience {
  name: String!
  similarExperiences: [Experience!]!
}
```
The mock is generating errors since it doesn't control this function execution.

**Comment by ardeois** [comment]
Yes, this is a know behaviour that I'm not sure how to fix.

An alternative would be to define an override for `similarExperiences` like this:

```javascript
anExperience({
   similarExperiences: []
})
```

**Comment by molandim** [comment]
One approach was to have a second parameter in all functions to disable recursive invocations.

**Comment by ardeois** [comment]
But we would have to detect if we are creating recursive invocations or not.
Feel free to create a pull request if you have ideas

**Comment by ford-outreach** [comment]
I ran into this issue and have opened a pull request with a possible solution. Please let me know if this approach seems reasonable. I believe it would solve my use case.
https://github.com/ardeois/graphql-codegen-typescript-mock-data/pull/31
