### ISSUE TITLE
Name convention

### ISSUE THREAD

**Issue by molandim** [ardeois/graphql-codegen-typescript-mock-data#14]
By default typescript resolvers transform objects name to pascalCase. The same doesn't happen with the mocks functions.

I have an object called `additionalInfo` that typescript resolver transformed to `AdditionalInfo` but the mock generated is trying to import as lower case.

**Comment by ardeois** [comment]
Yes we follow [Airbnb's convention](https://github.com/airbnb/javascript#naming-conventions) where classes and types should be PascalCase, but function are camel case.

The mock function should then be named `anAdditionalInfo`

If that's not the case, feel free to open a PR, or provide some code to reproduce

**Comment by ardeois** [comment]
@molandim new option that could help you
https://github.com/ardeois/graphql-codegen-typescript-mock-data#typenames-string-defaultvalue-pascal-casepascalcase
