### ISSUE TITLE
Create a value based on the key name

### ISSUE THREAD

**Issue by liorpevzner** [ardeois/graphql-codegen-typescript-mock-data#153]
Hi got a question.
Is it possible or maybe a future feature to add GeneratorOptions based on the key name?
for example if I have an type
type User {
  userId: String!
}

when the mock will be generated for the User, userId will be mapped to a random string.
Is it possible to check if the key has a certain regex inside of it and generate a faker based response? I understand that userId should be defined as an ID and that can solve my problems, buy maybe thats a useful feature anyway.

**Comment by ardeois** [comment]
@liorpevzner sorry for the delay
We already have [fieldGeneration](https://github.com/ardeois/graphql-codegen-typescript-mock-data?tab=readme-ov-file#fieldgeneration--typename-string--fieldname-string-generatoroptions---defaultvalue-undefined) option already
It doesn't accept regex but you can decide which faker generator to use for a specific field

Is this answering your question?
