### ISSUE TITLE
Upgrade to faker 8

### ISSUE THREAD

**Issue by bmulholland** [ardeois/graphql-codegen-typescript-mock-data#168]
I just spent 15 minutes trying to debug because person.fullName wasn't working. It's only available in v8, and v9 is coming along.

See also https://github.com/ardeois/graphql-codegen-typescript-mock-data/pull/134

**Comment by ardeois** [comment]
Fixed in major version bump 4.0.0
https://github.com/ardeois/graphql-codegen-typescript-mock-data/pull/169

**Comment by bmulholland** [comment]
Wow that was fast! Thank you <3 <3

**Comment by bmulholland** [comment]
You gotta laugh hahaha: https://github.com/faker-js/faker/releases/tag/v9.0.0
