### ISSUE TITLE
@graphql-codegen/client-preset 4.4.0 breaks generated mock file

### ISSUE THREAD

**Issue by bmulholland** [ardeois/graphql-codegen-typescript-mock-data#173]
https://github.com/dotansimha/graphql-code-generator/pull/10073 drops a bunch of types that this plugin relies on

I've filed it as https://github.com/dotansimha/graphql-code-generator/issues/10167

**Comment by bmulholland** [comment]
Not actually a bug in this lib, but this was one of the first places I looked, so adding here in case it saves others time

**Comment by ardeois** [comment]
Seems like they reverted the code. It now works with version 4.5.0, so closing this issue
