### ISSUE TITLE
Usage along with globally exported types

### ISSUE THREAD

**Issue by RicardoTrindade** [ardeois/graphql-codegen-typescript-mock-data#28]
Have a question regarding the usage along with the `add` plugin https://graphql-code-generator.com/docs/plugins/add

We're using this plugin to have our types globally available, so our generated types file looks like this
```
declare namespace Api {
  type Payment  = { 
    id: Scalars['Int'];
  }
...
}
```
When using the generated types we don't need to import them and call `Api.Payment`directly.

Now when using it with the mock data generator the mocks are generated as follows 
```
export const mockPayment = (overrides?: Partial<Payment>): Payment => {
}
```

which is not working as the type should have the `Api.` prefix to compile successfully.
Is this something you are considering to support or are accepting a PR any time soon ?

**Comment by ardeois** [comment]
@RicardoTrindade Yes sure if we can find a way for you to use this plugin, I'm all for it!

I'm accepting pull requests, but I'm not sure how we could support this kind of behaviour.
I think of 2 possible solutions:
- Use `add` plugin to the generated file so we add custom code and provide all types without the namespace (but only for this generated file). But I'm not sure if that's possible
- Add a new option like `typesPrefix: 'Api.'`

Ideally if we can find a combination without adding new options that would be great

**Comment by RicardoTrindade** [comment]
Closing the issue since the PR is closed. Thanks for your help!
