### ISSUE TITLE
Option to generate plain JS without types?

### ISSUE THREAD

**Issue by FezVrasta** [ardeois/graphql-codegen-typescript-mock-data#36]
Hi, is there any option to generate the mock data in plain JavaScript?

**Comment by ardeois** [comment]
Hi @FezVrasta no sorry there isn't
But you could maybe run `tsc` on the file to convert it to plain javascript

**Comment by FezVrasta** [comment]
Is there any technical reason behind this behavior?

**Comment by ardeois** [comment]
Yes it's because this plugin is named **typescript**-mock-data and we generate types in the code directly. 
Feel free to fork this project and create a plugin **javascript**-mock-data maybe?

**Comment by FezVrasta** [comment]
No need to be rude.

**Comment by ardeois** [comment]
Sorry @FezVrasta I didn't mean to be rude, but ze don't use any templating system so generating a different output, would require a huge refactor.
Like many open source projects, it was done in few hours during a week end, so it's not perfect
