### ISSUE TITLE
Mocking Gql Fragments

### ISSUE THREAD

**Issue by andreialecu** [ardeois/graphql-codegen-typescript-mock-data#38]
Hey! Just found this library and it's looking great!

One minor issue we're having is that we use gql fragments extensively, and the props we pass to our react components are of the `Fragment` type (eg. `UserFragment`).

It seems like the generator doesn't mock fragments currently, so we need to use the full type - which results in some TS errors unless an assertion is added (`aUser(...) as UserFragment`).

Would mocking fragments be possible via a config flag?

**Comment by ardeois** [comment]
Hey @andreialecu, thanks for the interest on this library.

That's a good point we actually have a similar issue in our code at my company. However I don't have time to improve the lib right now, but PRs are welcomed !
