### ISSUE TITLE
PR for correction import of types with correct typesPrefix including typesPrefix for enums

### ISSUE THREAD

**Issue by kraegpoeth** [ardeois/graphql-codegen-typescript-mock-data#51]
Hi @ardeois !

Super cool library, we are looking to use this in our production setup. Found a couple bugs though so would like to open a PR for feature changes. Let me know what you think!
Fixes 
- Import of types from generated.ts does not correctly add typesPrefix. 
- Enums does not apply typesPrefix correctly.

I've fixed these locally - how to contribute? :) 

Ps. Should probably add another config var `enumsPrefix` as this correctly mirrors the config settings of [typescript-operations plugin](https://www.graphql-code-generator.com/docs/plugins/typescript-operations) (see typesPrefix and enumsPrefix)

pps. how come you are not listed in the official graphql-codegen plugin list!? You deserve that! 🙏

**Comment by ardeois** [comment]
@kraegpoeth thanks for the feedback

Yes it makes sense to add `enumsPrefix` similar to typescript-operations-plugin
As for the import types, it's probably a bug, I didn't see the issue in my use case.

To contribute you can fork the repository and open a PR.
I suggest to open 1 PR for each use case. Make sure to add unit tests as well please.

> pps. how come you are not listed in the official graphql-codegen plugin list!? You deserve that! 🙏

Haha thanks, I should probably contact them and hand over the ownership of the repo. But to be honest I'm not very proud of the code itself, I developed this project on my spare time and didn't give enough love in term of code quality

**Comment by jordan-paz** [comment]
> Import of types from generated.ts does not correctly add typesPrefix.

I'm having this same issue. @kraegpoeth would you mind sharing your solution? 🙏

**Comment by ardeois** [comment]
@kraegpoeth this PR should fix the first part of your issue
I'll check for `enumsPrefix` what I can do

**Comment by ardeois** [comment]
@kraegpoeth `enumsPrefix` added in version [1.6.0](https://github.com/ardeois/graphql-codegen-typescript-mock-data/releases/tag/v1.6.0)
