### ISSUE TITLE
Usage with near-operation-file-preset?

### ISSUE THREAD

**Issue by leggomuhgreggo** [ardeois/graphql-codegen-typescript-mock-data#73]
Hello! I was wondering if there's any way to use the plugin with [`near-operation-file-preset` plugin](https://www.graphql-code-generator.com/plugins/near-operation-file-preset), so that the factories are shaped/co-located with respect to individual `.graphql` documents.

Thanks!

**Comment by ardeois** [comment]
Hi @leggomuhgreggo 
I don't know this plugin, but if I understand well, it's splitting the generated operations into separate files

Right now there is no such features, but if there is an interest, we could think about how it could be implemented

**Comment by leggomuhgreggo** [comment]
I appreciate your being willing to consider!

_For a little extra context:_
I'm hoping there's a way to generate factories so they mirror each operation, individually. That way, when we're testing, the TypeScript definitions don't require extra handling, in order to get the whole-type factory, to work with a partial-type operation query. 

(And thanks a bunch for the cool library!)

**Comment by wladimirgramacho** [comment]
@ardeois My team would be very interested in what @leggomuhgreggo proposed: 
> a way to generate factories so they mirror each operation, individually
Despite the fact that we're not using [near-operation-file-preset plugin](https://www.graphql-code-generator.com/plugins/near-operation-file-preset), we have been looking for a way to auto-generate mocked responses for operations defined on our GQL schema. These mocked responses could then be used in our tests and Storybook.
